name: "Foundry Multibuild"
author: "Paul Razvan Berg"
branding:
  color: "yellow"
  icon: "target"
description: "Test that a Foundry project can be built with a range of Solidity versions"
inputs:
  min:
    description: "Minimum Solidity version to build with"
    default: "0.8.0"
    required: true
  max:
    description: "Maximum Solidity version to build with"
    default: "0.8.23"
    required: true
  skip-test:
    description: "Whether to skip compiling the test directory"
    default: "true"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Install Foundry"
      uses: "foundry-rs/foundry-toolchain@v1"

    - name: "Add the action path to the runner system path"
      run: echo "${{ github.action_path }}/src" >> $GITHUB_PATH
      shell: bash

    - name: "Run the multibuild script"
      run: >-
        multibuild.sh
        --min ${{ inputs.min }}
        --max ${{ inputs.max }}
        --skip-test ${{ inputs.skip-test }}
      shell: "bash"

    - name: "Write to job summary"
      run: |
        echo "## Foundry Multibuild" >> $GITHUB_STEP_SUMMARY
        echo "✅ Compiled with all Solidity versions from v${{ inputs.min }} to v${{ inputs.max }}" >> $GITHUB_STEP_SUMMARY
      shell: "bash"
