name: "Foundry Multibuild"
author: "Paul Razvan Berg"
branding:
  color: "yellow"
  icon: "target"
description: "Test that a Foundry project can be built with a range of Solidity versions"
inputs:
  min:
    description: "Minimum Solidity version to build with"
    required: true
    default: "0.8.0"
  max:
    description: "Maximum Solidity version to build with"
    required: true
    default: "0.8.23"
runs:
  using: "composite"
  steps:
    - name: "Install Foundry"
      uses: "foundry-rs/foundry-toolchain@v1"

    - name: "Build the project with all Solidity versions supplied"
      shell: "bash"
      run: "./src/multibuild.sh ${{ inputs.min }} ${{ inputs.max }}"

    - name: "Write to job summary"
      shell: "bash"
      run: |
        echo "## Foundry Multibuild Check" >> $GITHUB_STEP_SUMMARY
        echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
